vincentwolsink/home_assistant_enphase_envoy_installer

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py
I have two relays in my setup, which are also available through this newly discovered endpoint 😄 
And i already had a custom entity for firmware status of the envoy, so i just added this as well.
Unfortunately, the relays only report back if they are open/closed (and no voltage/hertz stats), but at least it's something.
The relays appear in both the pcu (where inverters live as well), and in the nsrb output, so they had to be filtered out in the `inverters_status` method.
Some example output from my env:
```json
{
"counters": {
"pcu": {
"expected": 14,
"discovered": 14,
"ctrlsTotal": 14,
"ctrlsGone": 0,
"ctrlsCommunicating": 14,
"chansTotal": 14,
"chansRecent": 14,
"chansProducing": 14
},
"acb": {
"expected": 0,
"discovered": 0,
"ctrlsTotal": 0,
"ctrlsGone": 0,
"ctrlsCommunicating": 0, …
```
=> Add firmware status entity and relays

custom_components/enphase_envoy/envoy_reader.py
Certain Envoy firmwares require the usage of a session cookie (although this is not according to their API spec).
=> Implement usage of session cookie

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/strings.json, custom_components/enphase_envoy/translations/en.json, custom_components/enphase_envoy/translations/nl.json
When the CT is logically wired behind the Relay, it will measure about 3.5 watts of usage per relay. So a small relay usage when the sun is down should not be counted as real production value, but just report a production value of 0 watts.
=> Prevent negative production values, for small negative

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py, custom_components/enphase_envoy/strings.json, custom_components/enphase_envoy/translations/en.json, custom_components/enphase_envoy/translations/nl.json
This can be turned on using configuration, and is disabled by default It will only update the phase sensors entities, as these sensors are fed back from the endpoint. The default consumption/production/etc entities are still polled and updated every minute (unless configured otherwise)
Also implemented a interval/throttle to prevent a entity update overload for some systems (took this example from the dsmr reader component)
It will only update the phase sensors that actually hold some data.
It works for me (with 1phase metered), and it should not break non-metered envoys (but i could not fully test this)
=> Adding option to read realtime data from envoy using /stream/meter endpoint

README.md, custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/strings.json, custom_components/enphase_envoy/translations/en.json, custom_components/enphase_envoy/translations/nl.json
This option allows to not collect data that requires authorization through a installer or DIY account. Enabling the option will prevent repeated new enphase token collection and still have resulting 401 status from the envoy as latest firmware does not allow home owner account access to installer data.
When the integration is configured go to the configuration options, check the 'Do not collect data that requires installer or DIY enphase account' option and reload the integration.
=> Add configuration option to not collect data that requires installer or DIY account

custom_components/enphase_envoy/envoy_reader.py
=> If Envoy metered without CTs get lifetime_production from production.json

custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py
These sensors are not available for all configurations and since they are not that interesting with the built-in Home Assistant energy dashboard/features, might aswell remove them.
=> Remove seven day sensors

custom_components/enphase_envoy/envoy_reader.py
For the non-streaming endpoint we use `total-consumption` values, which are the values after Envoy did calculations. To keep the streaming endpoint values equal we should use them here too.
=> Use total-consumtion which is calculated consumption for streaming values

custom_components/enphase_envoy/envoy_reader.py
Get relay information from inventory if not existing in device status. Home Owner account users have no access to device status in newer firmware. Only missing information is the forced field.
=> Get relay information from inventory if not existing in device status to support Home owner account

custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_consumption_report.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_devstatus.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_home_json_results.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_info_results.xml, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_inventory_results.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_production_inverters.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_production_json_results.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_production_power.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_production_report.json, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_production_v1_results.json
And other updates:
- URL's are registered in a mapping, with some additional settings, like how often to fetch the url and if installer token is required
- The JWT token has a field for identifying the type of the token (owner or installer). This is now implemented in determining if we can fetch a url endpoint.
- Attributes can be referenced with jsonpath logic or be defined by @envoy_property wrappers. This way it is easier to add new measurements and also easier to differentiate between EnvoyStandard and Metered and Metered with CT.
- Because of the jsonpath logic, we can also use the non-None properties to get a list of endpoints we should update. Which urls are required are evaluated once, when one full getData call has completed.
I also included test data, so we can more easily test …
=> Updated envoy_reader with smarter fetching and fetching properties based on jsonpaths

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/envoy_reader.py
- Force loading the store from home assistant, when called from HA
> When testing it makes sense to store a token in self.data (to prevent fetching a new token, thus causing too many installer sessions on the envoy). Since tokens are stored in HA, we should keep using this token, eventhough we might have configured something else in envoy_reader.py
- Lets not send the auth_header every time, and use the cookie's session id
> Not sure if the auth header calls entrez every time, but since we're already authenticated, it would make sense to not send the bearer token on every request.
=> Envoy reader use session and fixate loading the store from HA upon init.

custom_components/enphase_envoy/envoy_reader.py
Attribute unknown message is a bit spammy for EnvoyStandard, when other variables are requested.
=> Do debug for unknown attributes that are not known in EnvoyData derivative class

custom_components/enphase_envoy/envoy_reader.py
Otherwise we might end up with a owner token. This will prevent polling the installer endpoint urls, which in its turn will prevent the privilege escalation.
So now we always query envoy procedure to fetch token, unless installer account is disabled (which is set if envoy procedure does not return a valid result too.
=> First token attempt should always be the envoy-procedure

custom_components/enphase_envoy/config_flow.py
The current zeroconf discovery will alternate updating the IP of the Envoy between IPv4 and IPv6 if the Envoy has both. This code prevents this and will only update the IP if it has a new address within the same IP version.
=> Only update ip via zeroconf if same version

custom_components/enphase_envoy/config_flow.py
With previous change the same envoy would be asked to be reconfigured every time.
=> Fix regression introduced in previous zeroconf changes

custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/test_data/envoy_metered/endpoint_pdm_energy.json
For Metered envoys without CT. It is a installed endpoint though.
=> Add pdm_energy endpoint to restore daily production values

custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/sensor.py, custom_components/enphase_envoy/switch.py
Looks way better with different icons based on the device class.
=> Remove the static icon, as the device_class already defines a icon in HA

custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py
And completely drop the endpoint_production_inverters (and it also gives more precision, so for display we suggest 0 precision)
We're already using the devstatus endpoint anyway, so now we can just use this data for free, and prevent one request to the envoy.
=> When using installer token, we can use endpoint_devstatus endpoint

custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py
Not really sure if it is what i expected, but so far it looks like this:
envoy device:
inverter device:
relay device:
=> Adding a product_id mapping to show more information about devices

custom_components/enphase_envoy/envoy_reader.py
To prevent caching the wrong state for an hour
=> Reduce production switch cache time

custom_components/enphase_envoy/number.py, custom_components/enphase_envoy/select.py, custom_components/enphase_envoy/switch.py
Some enitites where missing Envoy and serial in the name. This could cause issues when multiple Envoys are present.
=> Fix entity naming (make sure to always include device name)

custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/envoy_endpoints.py, custom_components/enphase_envoy/envoy_reader.py
[FIX: Configuration dialog not loading](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/commit/a23f4658731f76a1b68c6b610fb95385d196ac7e)
[FIX: First endpoint data not stored. FIX: Tries to update first insta…](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/commit/53ae7727b674ba6e7777de5c4b99e715833a03fe)
[Endpoint production_power is an installer endpoint](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/commit/bbf9a30382c75a1f31db2378bd49f1060f1da1e2)
=> Several bugfixes incl production/consumption entities being unavailable

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/strings.json, custom_components/enphase_envoy/translations/en.json, custom_components/enphase_envoy/translations/nl.json
For when the Envoy value is reset or wrong for some reason.
=> Add configuration option to correct lifetime production value

custom_components/enphase_envoy/const.py
I'm a Sunpower customer who replaced their PVS6 with an Enphase Envoy, this plugin is great, noticed it was missing our (special) inverters.  This patch fixes that
=> Add enphase built, sunpower only micro inverters (IQ7HS)

custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py
Since the new device data endpoint is not (always) available on firmware 7. Maybe we should implement endpoint differentiation per firmware at some point.
=> Fallback to old inverter production endpoint

custom_components/enphase_envoy/envoy_reader.py
While debugging #198, I was annoyed by that the result from "get grid profiles" doesn't get update, so I investigated this part, and realized `_clear_endpoint_cache` wasn't working correctly. This PR fixes that.
I also added an additional log to make clear the reason why some endpoints are not updated. This has helped me found the issue.
=> Fix _clear_endpoint_cache to correctly reset last fetch
