vincentwolsink/home_assistant_enphase_envoy_installer

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/config_flow.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py, custom_components/enphase_envoy/strings.json, custom_components/enphase_envoy/translations/en.json, custom_components/enphase_envoy/translations/nl.json
Removed duplicate code/logic.
Checkbox is gone. Now auto detects and shows if available. 
Handles CT readings being missing (not all CT clamps installed).
=> Refactored 3 phase readings

custom_components/enphase_envoy/const.py
These sensors can actually decrease as it is a cumulation of last seven days
=> Total increasing fix for seven days sensors

custom_components/enphase_envoy/envoy_reader.py
Once a 401 is raised upon fetching a url (not because of expired cookie), it will invoke self._getEnphaseToken().
If the token is still valid (and already set), it will use the envoy procedure, instead of owner token procedure.
This is a potential fix for #15 .
=> Reverse engineered login sequence that envoy uses to retrieve a token.

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/envoy_reader.py
When restarting a lot (for testing mostly), it occurred to me that the envoy was spitting out 503 errors. These are a indication of "Too many installer sessions active".
To fix this, we can just use an existing session, thus storing the authentication token on persistent storage would fix this problem.
(this link was discovered when fetching the https://envoy.local/auth/callback url, and interpreting the JS code; the JS code then would send you to https://envoy.local/err_toomanysess, which comes up with this explanation )
=> Store the authorization token in persistent storage to aid restarts

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py
It also reads the individual lines, if the're there.
=> Add voltage measurements from envoy

custom_components/enphase_envoy/envoy_reader.py
Should resolve https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/issues/47
(or at least the relays part)
=> Fix resolving data which results in only 1 dictionary

custom_components/enphase_envoy/envoy_reader.py
=> Fix recursion lookup error

custom_components/enphase_envoy/envoy_reader.py
If we're then using the installer token, you'd be using less endpoints eventually, as from the looks of it, we could reduce the amount of url's to query, if we're using a installer token since there is a lot of duplicate entries scattered accross several endpoints
=> Allow for different endpoints and paths for owner or installer tokens.

custom_components/enphase_envoy/envoy_reader.py
Hopefully this will prevent recursive calls more definitively, if they occur, we'd know sooner anyway.
=> Prevent recursive calls for EnvoyData

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/envoy_reader.py
Added methods for backward compatibility (which fetches the data from the EnvoyData class)
Also renamed some properties to match the EntityDescription.key as defined in const.py
This also removes the `__getattr__` method from the `EnvoyReader` class, making it a more straight forward class to read.
=> Refactoring how data is fetched and collected by datacoordinator.update

custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_reader.py
Entities added: connected state and forced state.
Also use self.relay as information endpoint, which is should be
token agnostic
=> Update name of relay entity and add some entities

custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py
Also fix the weird constant naming
=> Expose detected Envoy model

custom_components/enphase_envoy/envoy_reader.py
=> Fix missing syntax

custom_components/enphase_envoy/envoy_reader.py
so, forgot the formatting parameter.
=> Fix daily production values for phases

custom_components/enphase_envoy/__init__.py
According to traces the exceptions occured on the await task.
As i am unable to reproduce, i just added a try/except block, which should catch the error and allow for proper unload.
Potential fix for #81 and #83
=> Catch potential errors while awaiting the cancelled task.

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/services.yaml, custom_components/enphase_envoy/translations/en.json
This implements the feature mentioned in #107, and I've also tested locally that it works as expected.
=> Add upload_grid_profile service

custom_components/enphase_envoy/__init__.py
When HA fails to start (for whatever reason), no task is created. However, it still triggers the [`entry.async_on_unload` callback](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/blob/d471b7f2a2dc45e9359b8d0718cbf2e48e0e8c79/custom_components/enphase_envoy/__init__.py#L246) where it tries to cancel this task:
```
2024-05-14 05:53:12.347 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/enphase_envoy/__init__.py", line 240, in _async_stop
await _cancel_realtime_task(task)
File "/config/custom_components/enphase_envoy/__init__.py", line 255, in _cancel_realtime_task
task.cancel()
^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cancel'
```
I've …
=> Don't cancel non-existant task

custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/envoy_reader.py, test_data/envoy_metered/endpoint_ensemble_inventory.json
`home.json` is a very slow endpoint that in some cases even causes the integration to fail loading.
=> Stop reading from home.json

custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_endpoints.py, custom_components/enphase_envoy/sensor.py
Also reworked the classes inheritance a bit. To make it a bit more logical (to me at least).
=> Add firmware version sensors for all devices

custom_components/enphase_envoy/const.py
This reverts commit 0b6d1ff79a9c144655a1270f7b7fa846d26028bb.
=> Revert "Remove AC Current sensor, no correct readings"

custom_components/enphase_envoy/envoy_reader.py
=> Only read device_data for active devices

custom_components/enphase_envoy/envoy_reader.py
=> Make grid profile reading async to avoid HASS warning

custom_components/enphase_envoy/envoy_reader.py
=> Handle missing content-type in response headers

custom_components/enphase_envoy/binary_sensor.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/sensor.py
=> Handle missing report timestamps

custom_components/enphase_envoy/const.py
=> Add IQ8MC to mapping

custom_components/enphase_envoy/__init__.py, custom_components/enphase_envoy/const.py, custom_components/enphase_envoy/envoy_endpoints.py, custom_components/enphase_envoy/envoy_reader.py, custom_components/enphase_envoy/envoy_test_data.py, custom_components/enphase_envoy/services.yaml, custom_components/enphase_envoy/translations/en.json, test_data/envoy_metered/endpoint_dpel.json
Add services to allow enabling/disabling
Dynamic Power Export Limit
=> Add binary sensor for Dynamic Power Export Limit
